# Generated by Django 6.0.5 on 2026-05-14 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('num_guests', models.PositiveIntegerField()),
                ('food_preference', models.CharField(max_length=50)),
                ('attendance', models.CharField(choices=[('Will Attend', 'Will Attend'), ('Will Not Attend', 'Will Not Attend')], max_length=20)),
                ('personal_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
